const projectsData = [
    // ==================== END-TO-END PROJECTS ====================
    {
      id: 1,
      title: "Face Recognition with Real-Time Database",
      description: "A face recognition system that uses deep learning techniques and integrates with a real-time database for dynamic updates and recognition, perfect for security and attendance systems.",
      image: "https://github.com/SkikriHassane01/Face-Recognition-with-Real-Time-Database/blob/main/result.gif?raw=true",
      technologies: ["Python", "OpenCV", "Firebase", "Deep Learning", "React"],
      category: "End-to-End",
      tags: ["Face Recognition", "Real-time Database", "Security", "Attendance System", "Computer Vision"],
      githubLink: "https://github.com/SkikriHassane01/Face-Recognition-with-Real-Time-Database",
      demoLink: "",
      date: "2024-10-10"
    },
    {
      id: 2,
      title: "Automatic Number Plate Recognition",
      description: "Complete ANPR solution combining YOLOv8 for license plate detection and EasyOCR for text recognition, with a user-friendly interface and database integration for vehicle tracking.",
      image: "https://f5b623aa.delivery.rocketcdn.me/wp-content/uploads/elementor/thumbs/Blog_Automatic-Number-Plate-Recognition-ANPR-qmegp3g3wyfjqd2j53h4oltztud5quauv4cbfzkmww.jpg",
      technologies: ["Python", "YOLOv8", "EasyOCR", "OpenCV", "Flask"],
      category: "End-to-End",
      tags: ["Computer Vision", "OCR", "Vehicle Tracking"],
      githubLink: "https://github.com/SkikriHassane01/Automatic-number-plate-recognition-with-Yolov8-and-EasyOCR",
      demoLink: "",
      date: "2024-03-07"
    },
    {
      id: 3,
      title: "HealthAI: Intelligent Disease Detection",
      description: "AI platform for the quick and accurate diagnosis of major diseases through medical image analysis, featuring a web interface for image upload and results within minutes.",
      image: "https://www.damanhealth.ae/wp-content/uploads/2023/12/shutterstock_451054186-scaled.jpg",
      technologies: ["Python", "TensorFlow", "React", "Flask", "Medical Imaging"],
      category: "End-to-End",
      tags: ["Healthcare", "AI Diagnosis", "Medical Imaging", "Web Application"],
      githubLink: "https://github.com/SkikriHassane01/HealthAI_Intelligent-Disease-Detection",
      demoLink: "",
      date: "2024-06-04"
    },
    {
      id: 4,
      title: "Custom ChatBot with PyTorch and Azure OpenAI",
      description: "Fully functional chatbot system leveraging Azure OpenAI API and PyTorch for domain-specific conversational AI, including a web interface and context management.",
      image: "https://aunoa.ai/wp-content/uploads/2024/05/tipos-de-chatbots.webp",
      technologies: ["Python", "PyTorch", "Azure OpenAI", "React", "Flask"],
      category: "End-to-End",
      tags: ["Chatbot", "NLP", "Azure", "Conversational AI"],
      githubLink: "https://github.com/SkikriHassane01/Create-a-Custom-ChatBot-with-pytorch-and-Azure-OpenAi-API-model-",
      demoLink: "",
      date: "2024-07-12"
    },
    {
      id: 5,
      title: "COVID-19 Analysis with SQL & Tableau",
      description: "Comprehensive COVID-19 data analysis pipeline using SQL for data processing and Tableau for interactive dashboards, providing visual insights into pandemic trends.",
      image: "https://raw.githubusercontent.com/SkikriHassane01/Analyse_Covide19_with_SQL_Tableau/refs/heads/main/images/covid19.jpg",
      technologies: ["SQL", "Tableau", "Data Analysis", "Data Visualization"],
      category: "End-to-End",
      tags: ["COVID-19", "Dashboard", "Data Pipeline", "Public Health"],
      githubLink: "https://github.com/SkikriHassane01/Analyse_Covide19_with_SQL_Tableau",
      demoLink: "",
      date: "2024-09-07"
    },
    {
      id: 6,
      title: "Salary Prediction Application",
      description: "End-to-end salary prediction system deployed on AWS Elastic Beanstalk, featuring a machine learning model trained on industry data and a web interface for predictions.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOS77yPu3sm_TRoyc_ZRVy2FtujHySY78ZyQfzqaMdaRwurg5ntn8MvcDdH4ljIuuR0mk&usqp=CAU",
      technologies: ["Python", "Scikit-learn", "AWS", "Flask", "HTML/CSS/JS"],
      category: "End-to-End",
      tags: ["Salary Prediction", "AWS Deployment", "Machine Learning", "Web Application"],
      githubLink: "https://github.com/SkikriHassane01/Predict-Salary-application_deploy_Elastick_beanstalk",
      demoLink: "",
      date: "2023-11-19"
    },
    {
      id: 7,
      title: "House Price Prediction System",
      description: "Complete housing price prediction platform from research to production, featuring data processing, model training, evaluation, and a deployed web interface.",
      image: "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*3Psu7nDr2LvhWH4R6-Tqeg.jpeg",
      technologies: ["Python", "XGBoost", "Flask", "Docker", "AWS"],
      category: "End-to-End",
      tags: ["Real Estate", "Price Prediction", "Production ML", "Deployment"],
      githubLink: "https://github.com/SkikriHassane01/HousePrice_from_research_to_production_project",
      demoLink: "",
      date: "2024-02-15"
    },
    {
      id: 8,
      title: "Student Performance Predictor",
      description: "End-to-end ML application predicting student exam performance based on socioeconomic and academic factors, with a user-friendly interface for educators.",
      image: "https://storage.googleapis.com/kaggle-datasets-images/4302880/7400136/2274c7efc02a775080a121160d222d8f/dataset-cover.jpg?t=2024-01-14-12-06-04",
      technologies: ["Python", "Random Forest", "Flask", "Bootstrap", "SQLite"],
      category: "End-to-End",
      tags: ["Education", "Performance Prediction", "ML Application", "Student Analytics"],
      githubLink: "https://github.com/SkikriHassane01/Student-Exam-Performance-Predictor-end-to-end-project",
      demoLink: "",
      date: "2024-03-26"
    },
    {
      id: 9,
      title: "Poker Hand Detector",
      description: "Real-time poker hand recognition system using computer vision to identify cards and machine learning to determine poker hands, with a user interface for game assistance.",
      image: "https://raw.githubusercontent.com/hugofloter/CardsCVML/master/data_ex/ML/result3.jpg",
      technologies: ["Python", "OpenCV", "TensorFlow", "PyQt"],
      category: "End-to-End",
      tags: ["Card Recognition", "Game AI", "Computer Vision", "Pattern Recognition"],
      githubLink: "https://github.com/SkikriHassane01/Pocker-hand-detector",
      demoLink: "",
      date: "2023-05-28"
    },
    {
      id: 10,
      title: "Vehicle Counter with YOLOv8",
      description: "Traffic monitoring system for counting and classifying vehicles using YOLOv8 object detection, with statistics generation and visualization capabilities.",
      image: "https://images.unsplash.com/photo-1527430253228-e93688616381?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      technologies: ["Python", "YOLOv8", "OpenCV", "Streamlit"],
      category: "End-to-End",
      tags: ["Traffic Analysis", "Object Detection", "Computer Vision", "Urban Planning"],
      githubLink: "https://github.com/SkikriHassane01/Car-Counter-project-with-yolov8",
      demoLink: "",
      date: "2024-06-28"
    },
  
    // ==================== COMPUTER VISION PROJECTS ====================
    {
      id: 11,
      title: "PAN Card Tampering Detection",
      description: "Computer vision system that detects tampering in Indian PAN card documents through image processing techniques, deployed as a Heroku web application.",
      image: "https://www.idfy.com/wp-content/uploads/2021/09/PAN-Tampering.png",
      technologies: ["Python", "OpenCV", "Image Processing", "Flask", "Heroku"],
      category: "Computer Vision",
      tags: ["Document Verification", "Forgery Detection", "Image Processing", "Security"],
      githubLink: "https://github.com/SkikriHassane01/PAN-card-tempering-detection_deployed_heroku",
      demoLink: "https://pan-card-tampering-detection-107600ec5681.herokuapp.com/",
      date: "2024-03-26"
    },
    {
      id: 12,
      title: "Object Detection using YOLO",
      description: "Implementation of various YOLO versions for real-time object detection in images and videos, with performance comparisons and use case demonstrations.",
      image: "https://raw.githubusercontent.com/SkikriHassane01/Object-Detection-using-Yolo/refs/heads/main/image.png",
      technologies: ["Python", "YOLO", "OpenCV", "Deep Learning"],
      category: "Computer Vision",
      tags: ["Object Detection", "YOLO", "Real-time Vision", "Deep Learning"],
      githubLink: "https://github.com/SkikriHassane01/Object-Detection-using-Yolo",
      demoLink: "",
      date: "2023-05-17"
    },
    {
      id: 13,
      title: "Virtual Calculator",
      description: "Augmented reality calculator interface controlled through hand gestures and finger movements, using computer vision for gesture recognition.",
      image: "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      technologies: ["Python", "OpenCV", "MediaPipe", "Computer Vision"],
      category: "Computer Vision",
      tags: ["Gesture Recognition", "AR", "Human-Computer Interaction", "Computer Vision"],
      githubLink: "https://github.com/SkikriHassane01/Virtual-Calculator-project-",
      demoLink: "",
      date: "2023-07-04"
    },
    {
      id: 14,
      title: "Text Extraction Project",
      description: "Advanced OCR system for extracting text from various document types and complex backgrounds, with preprocessing for improved accuracy.",
      image: "https://quixy.com/wp-content/uploads/2022/04/Intelligent-text-extraction.png",
      technologies: ["Python", "Tesseract OCR", "OpenCV", "Image Processing"],
      category: "Computer Vision",
      tags: ["OCR", "Text Extraction", "Document Processing", "Information Retrieval"],
      githubLink: "https://github.com/SkikriHassane01/Text-Extraction-Project",
      demoLink: "",
      date: "2024-02-27"
    },
    {
      id: 15,
      title: "Image Watermarking",
      description: "Digital image watermarking system using both visible and invisible techniques to protect image copyright while preserving quality.",
      image: "https://www.digitalguardian.com/sites/default/files/styles/og_image/public/Watermarking%2520Image.jpg?itok=WiLNBJy2",
      technologies: ["Python", "OpenCV", "Pillow", "Signal Processing"],
      category: "Computer Vision",
      tags: ["Digital Watermarking", "Copyright Protection", "Image Processing", "Security"],
      githubLink: "https://github.com/SkikriHassane01/Image-Watermarking",
      demoLink: "",
      date: "2024-06-16"
    },
  
    // ==================== DEEP LEARNING PROJECTS ====================
    {
      id: 16,
      title: "Next Word Prediction",
      description: "Deep learning model for predicting the next word in a sentence using LSTM networks, trained on a diverse corpus with contextual understanding.",
      image: "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*_MrDp6w3Xc-yLuCTbco0xw.png",
      technologies: ["Python", "TensorFlow", "LSTM", "NLP"],
      category: "Deep Learning",
      tags: ["Text Prediction", "NLP", "Sequence Modeling", "Language Model"],
      githubLink: "https://github.com/SkikriHassane01/Predicting_TheNext_Word_",
      demoLink: "",
      date: "2023-07-22"
    },
    {
      id: 17,
      title: "Movie Review Sentiment Analysis",
      description: "RNN-based sentiment analysis model for movie reviews, categorizing text as positive or negative with high accuracy and explanation capabilities.",
      image: "https://raw.githubusercontent.com/SkikriHassane01/Movie_Review_SimpleRNN_project/refs/heads/main/image.png",
      technologies: ["Python", "RNN", "TensorFlow", "NLP"],
      category: "Deep Learning",
      tags: ["Sentiment Analysis", "NLP", "Text Classification", "Movie Reviews"],
      githubLink: "https://github.com/SkikriHassane01/Movie_Review_SimpleRNN_project",
      demoLink: "",
      date: "2023-11-16"
    },
    // {
    //   id: 18,
    //   title: "Customer Churn Classification with ANN",
    //   description: "Artificial Neural Network model for predicting customer churn, with feature importance analysis and actionable business insights.",
    //   image: "https://source.unsplash.com/800x600/?customer-analytics,graph",
    //   technologies: ["Python", "Keras", "ANN", "Pandas"],
    //   category: "Deep Learning",
    //   tags: ["Customer Churn", "ANN", "Business Analytics", "Classification"],
    //   githubLink: "https://github.com/SkikriHassane01/churn-classification-project-ann",
    //   demoLink: "",
    //   date: "2024-04-29"
    // },
    {
      id: 19,
      title: "Kindle Review Sentiment Analytics",
      description: "Deep learning system analyzing Amazon Kindle reviews for sentiment, feature importance, and trend analysis over time.",
      image: "https://private-user-images.githubusercontent.com/180952453/387879007-8e40638e-3fc5-45b6-8e65-a79fc5ce7af1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA5MTk3ODIsIm5iZiI6MTc0MDkxOTQ4MiwicGF0aCI6Ii8xODA5NTI0NTMvMzg3ODc5MDA3LThlNDA2MzhlLTNmYzUtNDViNi04ZTY1LWE3OWZjNWNlN2FmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwMlQxMjQ0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmQyNTJiMTM2YzdiMTI5MjhkMDVhNzEwODU2ZTU1YTVkNDRmZDgyYWM5Yzg4ODBiYTk1YmE1NGU3ODk1Yzg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3cW6nw_QCpE7gANmxzTrChabXNTgfdc_bwI6ddzs-ls",
      technologies: ["Python", "BERT", "TensorFlow", "NLP"],
      category: "Deep Learning",
      tags: ["NLP", "Sentiment Analysis", "Product Reviews", "BERT"],
      githubLink: "https://github.com/SkikriHassane01/Kindle-Review-Sentiment-Analytics",
      demoLink: "",
      date: "2023-09-28"
    },
    {
      id: 20,
      title: "Dog Breed Classification using Transfer Learning",
      description: "Image classification system identifying dog breeds using transfer learning with pre-trained CNN architectures, achieving high accuracy across 120+ breeds.",
      image: "https://miro.medium.com/v2/resize:fit:500/1*F5ZM40ejiJ84ZMkJMhp4Kw.jpeg",
      technologies: ["Python", "TensorFlow", "Transfer Learning", "CNN"],
      category: "Deep Learning",
      tags: ["Transfer Learning", "Image Classification", "Dog Breeds", "CNN"],
      githubLink: "https://github.com/SkikriHassane01/Dog-Breed-Classification-using-Transfer-learning",
      demoLink: "",
      date: "2023-06-26"
    },
    {
      id: 21,
      title: "COVID-19 Detection CNN",
      description: "Deep learning model for detecting COVID-19 infection from chest X-rays using custom CNN architecture, with validation on multiple datasets.",
      image: "https://media.defense.gov/2020/Mar/09/2002261406/1200/1200/0/200309-D-HN545-003.JPG",
      technologies: ["Python", "CNN", "TensorFlow", "Medical Imaging"],
      category: "Deep Learning",
      tags: ["COVID-19", "Medical Imaging", "CNN", "Disease Detection"],
      githubLink: "https://github.com/SkikriHassane01/Covid-19-detection-CNN",
      demoLink: "",
      date: "2024-04-12"
    },
    {
      id: 22,
      title: "Alzheimer's Detection CNN",
      description: "Convolutional neural network for early detection of Alzheimer's disease from brain MRI scans, classifying different stages of cognitive impairment.",
      image: "https://camo.githubusercontent.com/a9404dc2bd1fe6f49468879c6ff10394418ced5a461e495b193ffae6682f8052/68747470733a2f2f6d69722d73332d63646e2d63662e626568616e63652e6e65742f70726f6a6563745f6d6f64756c65732f646973702f32376136303832323439383035332e353633313361333461373937612e676966",
      technologies: ["Python", "Keras", "CNN", "Medical Imaging"],
      category: "Deep Learning",
      tags: ["Alzheimer's", "Neuroimaging", "Disease Detection", "CNN"],
      githubLink: "https://github.com/SkikriHassane01/Alzhaimer-detection-CNN",
      demoLink: "",
      date: "2023-12-19"
    },
    {
      id: 23,
      title: "Handwritten Digit Classification",
      description: "CNN-based system for recognizing handwritten digits with high accuracy, including preprocessing techniques for improved performance on real-world images.",
      image: "https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2023/08/wacom-stylus-handwriting-recognition.jpg",
      technologies: ["Python", "CNN", "TensorFlow", "Computer Vision"],
      category: "Deep Learning",
      tags: ["Digit Recognition", "Image Classification", "CNN", "MNIST"],
      githubLink: "https://github.com/SkikriHassane01/Image-Digit-Classification-using-CNN",
      demoLink: "",
      date: "2023-07-04"
    },
  
    // ==================== MACHINE LEARNING PROJECTS ====================
    {
      id: 24,
      title: "Spam Classification Project",
      description: "Text classification system for identifying spam messages using various machine learning algorithms, with feature engineering and model comparison.",
      image: "https://private-user-images.githubusercontent.com/180952453/387866077-932b2b59-dc4f-4269-9633-416fba69b7b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA5MTg5ODcsIm5iZiI6MTc0MDkxODY4NywicGF0aCI6Ii8xODA5NTI0NTMvMzg3ODY2MDc3LTkzMmIyYjU5LWRjNGYtNDI2OS05NjMzLTQxNmZiYTY5YjdiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwMlQxMjMxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmJlZTc4OWNlZTkyYzU5MDA4NDU4ZjU0NmU5NmJjYWMzN2UyY2IxMmE5MGRmOWY3OTgzY2YzMGY4ZThjZWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6xiVjXzgEms9MK8irF9YFmdwYAkXw0ZnTZqYo2tuiKU",
      technologies: ["Python", "Scikit-learn", "NLP", "Text Classification"],
      category: "Machine Learning",
      tags: ["Spam Detection", "Text Classification", "NLP", "Feature Engineering"],
      githubLink: "https://github.com/SkikriHassane01/Spam-Classification-project-",
      demoLink: "",
      date: "2024-05-15"
    },
    {
      id: 25,
      title: "California House Pricing Regression",
      description: "Regression model predicting California housing prices based on location and property features, with detailed feature importance analysis.",
      image: "https://ap.rdcpix.com/c57dc834c4bf52adcf2b6879d4c22bfbl-m2506038727rd-w960_h720.webp",
      technologies: ["Python", "Scikit-learn", "Regression Models", "Data Analysis"],
      category: "Machine Learning",
      tags: ["Real Estate", "Regression", "Price Prediction", "California Housing"],
      githubLink: "https://github.com/SkikriHassane01/CaliforniaHousePricingRegressionProject",
      demoLink: "",
      date: "2024-04-08"
    },
    {
      id: 26,
      title: "Laptop Price Prediction",
      description: "Machine learning model for predicting laptop prices based on specifications, with feature engineering for technical components and market trends.",
      image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      technologies: ["Python", "Random Forest", "Gradient Boosting", "Pandas"],
      category: "Machine Learning",
      tags: ["Price Prediction", "Product Pricing", "Regression", "Electronics"],
      githubLink: "https://github.com/SkikriHassane01/Laptop_Price_prediction",
      demoLink: "",
      date: "2023-12-26"
    },
    {
      id: 27,
      title: "Water Quality Prediction using H2O AutoML",
      description: "Automated machine learning approach to predicting drinking water potability using H2O AutoML, with model interpretability and feature importance analysis.",
      image: "https://mf.b37mrtl.ru/media/pics/2023.08/article/64d165cc4c59b7210a6a10c2.jpg",
      technologies: ["Python", "H2O AutoML", "Water Analysis", "Classification"],
      category: "Machine Learning",
      tags: ["AutoML", "Water Quality", "Environmental", "Classification"],
      githubLink: "https://github.com/SkikriHassane01/Drinking-water-probability-prediction-using-H2O-AutoML",
      demoLink: "",
      date: "2023-01-21"
    },
    {
      id: 28,
      title: "Poisonous Mushroom Classification",
      description: "Binary classification model for identifying poisonous mushrooms using physical characteristics, optimized for high recall to prioritize safety.",
      image: "https://camo.githubusercontent.com/9e8b8413ddf235eba6ae811caae2e14443da5824d41722a27d4e33de61c2a7b4/68747470733a2f2f7777772e776f726c6461746c61732e636f6d2f722f77323030302d68313132352d7139302f75706c6f61642f66322f33392f37312f7368757474657273746f636b2d3530383136373638322e6a7067",
      technologies: ["Python", "H2O", "Classification", "Data Analysis"],
      category: "Machine Learning",
      tags: ["Binary Classification", "Food Safety", "Mushroom Identification", "H2O"],
      githubLink: "https://github.com/SkikriHassane01/Binary-Prediction-of-Poisonous-Mushrooms-with-h2o",
      demoLink: "",
      date: "2024-06-24"
    },
    {
      id: 29,
      title: "Bank Customer Churn Classification",
      description: "Predictive model for bank customer churn with feature importance analysis and customer segmentation for targeted retention strategies.",
      image: "https://fnh.ma//uploads/actualites/63ff4bd94f6e9_bank%20maroc.jpg",
      technologies: ["Python", "Scikit-learn", "XGBoost", "Customer Analytics"],
      category: "Machine Learning",
      tags: ["Banking", "Customer Churn", "Classification", "Business Analytics"],
      githubLink: "https://github.com/SkikriHassane01/Binary-Classification-with-a-Bank-Churn-Dataset",
      demoLink: "",
      date: "2023-05-07"
    },
    {
      id: 30,
      title: "Obesity and CVD Risk Prediction",
      description: "Machine learning model for predicting obesity and cardiovascular disease risk based on lifestyle and medical factors, with interpretable results.",
      image: "https://camo.githubusercontent.com/cf2e861418f741274899056f890ff6c1b74e1e965b23b4748a0ee0d64680c292/68747470733a2f2f692e70696e696d672e636f6d2f6f726967696e616c732f61352f34662f62652f61353466626564623861326163306164376438393065653336393931663937652e676966",
      technologies: ["Python", "Logistic Regression", "Random Forest", "Health Analytics"],
      category: "Machine Learning",
      tags: ["Healthcare", "Risk Assessment", "Preventive Medicine", "Classification"],
      githubLink: "https://github.com/SkikriHassane01/Obesity-or-CVD-risk-Prediction",
      demoLink: "",
      date: "2024-02-20"
    },
    {
      id: 31,
      title: "Titanic Survival Classification",
      description: "Machine learning model predicting passenger survival on the Titanic, with feature engineering for demographic and socioeconomic factors.",
      image: "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/f5da6224344869.56332ceebbbef.jpg",
      technologies: ["Python", "Scikit-learn", "Feature Engineering", "Classification"],
      category: "Machine Learning",
      tags: ["Kaggle Competition", "Historical Data", "Survival Prediction", "Classification"],
      githubLink: "https://github.com/SkikriHassane01/Titanic-classification-kaggle-competition",
      demoLink: "",
      date: "2023-01-22"
    },
    {
      id: 32,
      title: "Horse Health Prediction",
      description: "Veterinary machine learning model predicting horse health outcomes based on symptoms and medical measurements, for early intervention decision support.",
      image: "https://feedsnneeds.ca/wp/wp-content/uploads/2020/12/Maintaining-your-horses-health.png",
      technologies: ["Python", "Random Forest", "Medical Analysis", "Pandas"],
      category: "Machine Learning",
      tags: ["Veterinary Medicine", "Health Prediction", "Animal Health", "Classification"],
      githubLink: "https://github.com/SkikriHassane01/Horse-health-prediction",
      demoLink: "",
      date: "2024-09-26"
    },
    {
      id: 33,
      title: "Diabetes Detection",
      description: "Machine learning model for early diabetes detection using health metrics and patient history, with emphasis on interpretability for medical use.",
      image: "https://camo.githubusercontent.com/7a18475489d2ce77cbab1cb758c61ddac5c4b2d99acac8861490f94b5ddd35b9/68747470733a2f2f61637469766f2e636f2e7a612f77702d636f6e74656e742f75706c6f6164732f312d312d31343030783738382e706e67",
      technologies: ["Python", "Gradient Boosting", "Healthcare ML", "Feature Selection"],
      category: "Machine Learning",
      tags: ["Healthcare", "Diabetes", "Early Detection", "Screening"],
      githubLink: "https://github.com/SkikriHassane01/Diabetes_detection_from_research_to_deployment",
      demoLink: "",
      date: "2024-10-17"
    },
    {
      id: 34,
      title: "Software Defect Classifier",
      description: "Machine learning system for identifying potential defects in software code based on static analysis metrics and historical defect patterns.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtZkBrVvJIKpvWEZvxMkk2W8GZrUzbOclIChkmq7OouWZ18bJeS5GNuthNiYdbp95sfK8&usqp=CAU",
      technologies: ["Python", "Scikit-learn", "Software Metrics", "Classification"],
      category: "Machine Learning",
      tags: ["DevOps", "Quality Assurance", "Software Engineering", "Defect Prediction"],
      githubLink: "https://github.com/SkikriHassane01/Software-defect-classifier",
      demoLink: "",
      date: "2024-01-03"
    },
    {
      id: 35,
      title: "Breast Cancer Detection",
      description: "Machine learning model for breast cancer detection from diagnostic features, optimized for high sensitivity while maintaining specificity.",
      image: "https://camo.githubusercontent.com/b0bce76466ed2b759bac0a019b4e0daedbfe2446923b0505be849d6ede634c82/68747470733a2f2f74682e62696e672e636f6d2f74682f69642f4f49502e74504f3250345f6f52684156335f5059724477306251486145383f72733d31267069643d496d674465744d61696e",
      technologies: ["Python", "SVM", "Ensemble Methods", "Medical Diagnostics"],
      category: "Machine Learning",
      tags: ["Cancer Detection", "Medical Diagnostics", "Healthcare", "Classification"],
      githubLink: "https://github.com/SkikriHassane01/Breast-Cancer-detection",
      demoLink: "",
      date: "2024-02-12"
    },
  
    // ==================== WEB SCRAPING PROJECTS ====================
    {
      id: 36,
      title: "Quotes Scraping with Streamlit",
      description: "Web scraping application that extracts inspirational quotes from various websites and presents them in a Streamlit interface with filtering capabilities.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyqsw9s5P8FzLR9_AFtzo9GypLr01PKFwbaAKZxpDfAqLbWch2fbOt8U-WRxSfGXB5FeQ&usqp=CAU",
      technologies: ["Python", "Streamlit", "BeautifulSoup", "Web Scraping"],
      category: "Web Scraping",
      tags: ["Quotes Collection", "Web Scraping", "Data Extraction", "Streamlit"],
      githubLink: "https://github.com/SkikriHassane01/Quotes-Scraping-with-streamlit",
      demoLink: "",
      date: "2023-09-08"
    },
    {
      id: 37,
      title: "Wikipedia Web Scraper",
      description: "Customizable Wikipedia scraping tool for extracting structured information from articles, with export capabilities and citation tracking.",
      image: "https://www.parsehub.com/blog/content/images/size/w2000/2019/10/scrape-wikipedia-articles.jpg",
      technologies: ["Python", "BeautifulSoup", "Pandas", "Requests"],
      category: "Web Scraping",
      tags: ["Wikipedia", "Information Extraction", "Research Tool", "Web Scraping"],
      githubLink: "https://github.com/SkikriHassane01/Wikipedia-Web-Scraper",
      demoLink: "",
      date: "2024-02-26"
    },
  
    // ==================== DATA ANALYSIS PROJECTS ====================
    {
      id: 38,
      title: "Zomato Data Analysis",
      description: "Comprehensive analysis of Zomato restaurant data using pandas and seaborn, revealing insights about cuisines, locations, pricing, and customer preferences.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtyFKlkWU_6nHeereWYNbVPdZNICMnrVOsctgGMs2Upkfu8yv6smn3ua9_028-r4QqGng&usqp=CAU",
      technologies: ["Python", "Pandas", "Seaborn", "Data Analysis"],
      category: "Data Analysis",
      tags: ["Restaurant Analytics", "Food Industry", "Visualization", "Location Analysis"],
      githubLink: "https://github.com/SkikriHassane01/Zomato-Data-Analysis-using-pandas-and-seaborn",
      demoLink: "",
      date: "2023-05-31"
    },
    {
      id: 39,
      title: "IPL Auction Dataset Analysis",
      description: "Analysis of Indian Premier League cricket auction data from 2008-2024, showing player valuation trends, team strategies, and market evolution.",
      image: "https://www.simplilearn.com/ice9/free_resources_article_thumb/IPL_banner.jpg",
      technologies: ["Python", "Pandas", "Matplotlib", "Data Analysis"],
      category: "Data Analysis",
      tags: ["Sports Analytics", "Cricket", "IPL", "Auction Data"],
      githubLink: "https://github.com/SkikriHassane01/IPL-2008-2024-Auction-dataset-analysis",
      demoLink: "",
      date: "2024-08-08"
    },
    {
      id: 40,
      title: "COVID-19 Analysis and Visualization",
      description: "Interactive visualization of COVID-19 pandemic data using Plotly Express, showing geographic spread, time trends, and comparative analysis.",
      image: "https://camo.githubusercontent.com/cc46b0a4ff512f66425dca3d891ffc4e485e83a0408917a6dafcff2a8c7f76a3/68747470733a2f2f6d656469612e6c6963646e2e636f6d2f646d732f696d6167652f76322f443536313241514879423132714246734c48772f61727469636c652d636f7665725f696d6167652d736872696e6b5f3732305f313238302f61727469636c652d636f7665725f696d6167652d736872696e6b5f3732305f313238302f302f313639383233393933363131383f653d3137343636363234303026763d6265746126743d483251746343535a3650756668364365774b6e315079743032304b796765727a3248782d7145702d464373",
      technologies: ["Python", "Plotly Express", "Pandas", "Data Visualization"],
      category: "Data Analysis",
      tags: ["Pandemic Analysis", "Interactive Visualization", "Global Health", "Time Series"],
      githubLink: "https://github.com/SkikriHassane01/Covid-19-Analysis-and-Visualization-using-Plotly-Express",
      demoLink: "",
      date: "2023-04-14"
    },
    {
      id: 41,
      title: "Kaggle Datasets Analysis",
      description: "Collection of analyses on various Kaggle datasets, demonstrating data cleaning, exploratory analysis, visualization, and insight extraction.",
      image: "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*JSbnt_mxpFfkGtNtGbR40g.png",
      technologies: ["Python", "Pandas", "Matplotlib", "Seaborn"],
      category: "Data Analysis",
      tags: ["Exploratory Analysis", "Data Cleaning", "Visualization", "Multiple Datasets"],
      githubLink: "https://github.com/SkikriHassane01/Analyzing-Some-Kaggle-Datasets",
      demoLink: "",
      date: "2024-10-15"
    },
  
    // ==================== TUTORIAL PROJECTS ====================
    {
      id: 42,
      title: "Python Concepts from Basics to Advanced",
      description: "Comprehensive tutorial covering Python programming from fundamentals to advanced concepts, with practical examples and best practices.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJcr0aixMXUSBlvCsHc_kAYS9ksCHeZojV0U-hEi77UU3IMnKaRcyuLGoYVixiHRQKoY8&usqp=CAU",
      technologies: ["Python", "Programming", "Tutorial", "Data Structures"],
      category: "Tutorial",
      tags: ["Python Tutorial", "Learning Resource", "Programming Fundamentals", "Advanced Python"],
      githubLink: "https://github.com/SkikriHassane01/Master-Every-Concept-about-python-from-Basics-to-Advanced",
      demoLink: "",
      date: "2023-02-28"
    },
    {
      id: 43,
      title: "Data Science Roadmap",
      description: "Structured learning path for data science mastery, from foundational skills to advanced techniques, with project recommendations and resource links.",
      image: "https://private-user-images.githubusercontent.com/180952453/365686943-f1baf0a9-1a8e-4978-b3ec-93d4044419c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA4NjkxMDcsIm5iZiI6MTc0MDg2ODgwNywicGF0aCI6Ii8xODA5NTI0NTMvMzY1Njg2OTQzLWYxYmFmMGE5LTFhOGUtNDk3OC1iM2VjLTkzZDQwNDQ0MTljOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwMVQyMjQwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjlkYTc3MzdmYzM4N2IwN2JiNDEwZWU0N2VkMjM4MTgwOTJiZGI5N2Y5ZDE0Y2IyOGExNzNhNWM5ZDhiNjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ldINPjR2pyaZ5e8mdSvyS64zgi3TLjtOd_rbjlbjMcg",
      technologies: ["Data Science", "Python", "Machine Learning", "Statistics"],
      category: "Tutorial",
      tags: ["Learning Path", "Data Science", "Career Guide", "Educational"],
      githubLink: "https://github.com/SkikriHassane01/Data-Scienc-Roadmap-from-zero-to-hero",
      demoLink: "",
      date: "2024-09-28"
    },
    {
      id: 44,
      title: "Building a Complete Python Package",
      description: "Step-by-step guide to creating, documenting, testing, and publishing a Python package, following best practices for modern Python development.",
      image: "https://media2.dev.to/dynamic/image/width=800%2Cheight=%2Cfit=scale-down%2Cgravity=auto%2Cformat=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F9urbqhg9sd62fzu6c1xj.png",
      technologies: ["Python", "Package Development", "PyPI", "Testing"],
      category: "Tutorial",
      tags: ["Python Packaging", "Development Guide", "Software Engineering", "Distribution"],
      githubLink: "https://github.com/SkikriHassane01/How-to-Build-a-Complete-Python-Package-Step-by-Step",
      demoLink: "",
      date: "2024-05-12"
    },
    {
      id: 45,
      title: "Feature Engineering in Machine Learning",
      description: "Comprehensive guide to feature engineering techniques for machine learning, covering selection, creation, transformation, and validation approaches.",
      image: "https://www.blog.trainindata.com/wp-content/uploads/2023/10/cover.gif",
      technologies: ["Python", "Scikit-learn", "Feature Engineering", "Machine Learning"],
      category: "Tutorial",
      tags: ["Feature Engineering", "ML Preprocessing", "Data Transformation", "Educational"],
      githubLink: "https://github.com/SkikriHassane01/Feature-Engineering-in-machine-learning",
      demoLink: "",
      date: "2024-08-30"
    },
    {
      id: 46,
      title: "Statistics and Probabilities for Data Science",
      description: "Educational repository covering essential statistical concepts and probability theory for data science applications, with Python implementations.",
      image: "https://statanalytica.com/blog/wp-content/uploads/2019/09/probability-vs-statistics.jpg",
      technologies: ["Python", "Statistics", "Probability", "NumPy"],
      category: "Tutorial",
      tags: ["Statistics", "Probability", "Data Science Foundations", "Learning Resource"],
      githubLink: "https://github.com/SkikriHassane01/Statistics-and-probabilities-for-data-science",
      demoLink: "",
      date: "2023-04-24"
    },
    {
      id: 47,
      title: "Plotly from Basic to Advanced",
      description: "Tutorial series on Plotly visualization library, covering basic charts to complex interactive dashboards with extensive examples.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqMH8nhsOKoWW64qyoKRzdXkAgdV9rBdJG0egV8KV1gWyotk1ElpVigpe2asdO-5TrSmI&usqp=CAU",
      technologies: ["Python", "Plotly", "Data Visualization", "Dashboarding"],
      category: "Tutorial",
      tags: ["Data Visualization", "Plotly", "Interactive Plots", "Dashboard Design"],
      githubLink: "https://github.com/SkikriHassane01/plotly-from-basic-to-advance",
      demoLink: "",
      date: "2024-07-16"
    },
    {
      id: 48,
      title: "Streamlit from Basic to Advanced",
      description: "Comprehensive guide to building data applications with Streamlit, from simple widgets to complex multi-page applications with state management.",
      image: "https://private-user-images.githubusercontent.com/180952453/412958455-b5691606-a4c6-46ae-acfd-5b9150b1181c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA5MzU0MzMsIm5iZiI6MTc0MDkzNTEzMywicGF0aCI6Ii8xODA5NTI0NTMvNDEyOTU4NDU1LWI1NjkxNjA2LWE0YzYtNDZhZS1hY2ZkLTViOTE1MGIxMTgxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwMlQxNzA1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTUwNTlkMmQ0NWFhMDQ2YjUxY2MzZDNlZGM3NzY2MzFhMWQ5MGNiODEzNjYyOGYxZDNlYWViNWMyZjU1YjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JxFC2GJkvqzAn4DCaeQQhSPppfC8wkzvlDiFfjkTKjQ",
      technologies: ["Python", "Streamlit", "Web Development", "Data Apps"],
      category: "Tutorial",
      tags: ["Streamlit", "Data Applications", "UI Development", "Dashboard Creation"],
      githubLink: "https://github.com/SkikriHassane01/Streamlit-from-basic-to-advance",
      demoLink: "",
      date: "2023-08-24"
    },
    {
      id: 49,
      title: "Machine Learning Algorithms From Scratch",
      description: "Implementation of core machine learning algorithms from mathematical principles, with detailed explanations and visualizations of internal workings.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVmPZhqtZTasQsAMSShPGt0RRSw0N1OPiPFYYn5E-KzbG7Ld7Evn9UpGkKYazAzeSHCZk&usqp=CAU",
      technologies: ["Python", "NumPy", "Mathematics", "Machine Learning"],
      category: "Tutorial",
      tags: ["Algorithm Implementation", "Educational", "ML Fundamentals", "Mathematics"],
      githubLink: "https://github.com/SkikriHassane01/Machine_Learning_Algorithme_From_Scratch",
      demoLink: "",
      date: "2023-09-02"
    },
    {
      id: 50,
      title: "Supervised ML Algorithms",
      description: "Detailed exploration of supervised machine learning algorithms with implementation examples, performance comparisons, and use case recommendations.",
      image: "https://camo.githubusercontent.com/fbfe106537044028e44d846831259d81d696be3e2a0b9255a2916123ecc487f6/68747470733a2f2f63646e2e626f7470656e6775696e2e636f6d2f6173736574732f776562736974652f537570657276697365645f4c6561726e696e675f326165346462633931322e706e67",
      technologies: ["Python", "Scikit-learn", "Supervised Learning", "Model Evaluation"],
      category: "Tutorial",
      tags: ["Supervised Learning", "Classification", "Regression", "Model Selection"],
      githubLink: "https://github.com/SkikriHassane01/Supervised_ML_algorithme",
      demoLink: "",
      date: "2024-11-30"
    },
    {
      id: 51,
      title: "Generative AI Complete Roadmap",
      description: "Comprehensive learning path for generative AI technologies, covering GANs, diffusion models, transformers, and practical implementation approaches.",
      image: "https://hekate.ai/wp-content/uploads/2024/01/generative-ai-la-gi.jpg",
      technologies: ["Python", "PyTorch", "TensorFlow", "Generative Models"],
      category: "Tutorial",
      tags: ["Generative AI", "Learning Path", "Deep Learning", "Educational"],
      githubLink: "https://github.com/SkikriHassane01/Full-Generative-Ai-Complete-Roadmap",
      demoLink: "",
      date: "2023-07-01"
    },
  
    // ==================== OTHER PROJECTS ====================
    {
      id: 52,
      title: "Portfolio Website with React",
      description: "Personal portfolio website built with React and Tailwind CSS, featuring interactive project showcase, theme switching, and integrated chatbot assistant.",
      image: "https://private-user-images.githubusercontent.com/180952453/418344645-93dd093c-430d-42b6-8a0d-e61730c537a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA5MTcxNjQsIm5iZiI6MTc0MDkxNjg2NCwicGF0aCI6Ii8xODA5NTI0NTMvNDE4MzQ0NjQ1LTkzZGQwOTNjLTQzMGQtNDJiNi04YTBkLWU2MTczMGM1MzdhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwMlQxMjAxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmY2ZDQ1NmE5NzM4NWVkMmI4NGU3NTA5YjdjNzdhYTM5NDkwZWZkODhkMGEzZWFiYmIyOThiOWVlMWMzODQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hgjMCaDLUXSzJYjEPCjKbBMiN0fXQO03ezFs4muoLmw",
      technologies: ["React", "Tailwind CSS", "JavaScript", "Framer Motion"],
      category: "Other",
      tags: ["Portfolio", "Web Development", "UI/UX", "Personal Branding"],
      githubLink: "https://github.com/SkikriHassane01/My_Portfolio",
      demoLink: "https://hassaneskikri.me/",
      date: "2023-07-12"
    },
    {
      id: 53,
      title: "RSA Cryptography Application",
      description: "Implementation of RSA encryption algorithm with educational visualization of the encryption/decryption process and key generation.",
      image: "https://raw.githubusercontent.com/SkikriHassane01/RSA-Application_crypto/refs/heads/main/image.png",
      technologies: ["Python", "Cryptography", "Mathematics"],
      category: "Other",
      tags: ["Encryption", "RSA", "Security", "Cryptography"],
      githubLink: "https://github.com/SkikriHassane01/RSA-Application_crypto",
      demoLink: "",
      date: "2024-03-12"
    },
    {
      id: 54,
      title: "To-Do App with Flask",
      description: "Web-based task management application built with Flask, featuring user authentication, task categories, priorities, and reminder functionality.",
      image: "https://mrctcenter.org/clinical-research-glossary/wp-content/uploads/sites/6/2021/06/Inclusion-CRITERIA-2-1536x962.png",
      technologies: ["Python", "Flask", "SQLite", "HTML/CSS/JS"],
      category: "Other",
      tags: ["Web Application", "Task Management", "Flask", "CRUD"],
      githubLink: "https://github.com/SkikriHassane01/ToDoWithFlask",
      demoLink: "",
      date: "2023-05-06"
    },
    {
      id: 55,
      title: "Kaggle Competitions",
      description: "Participation in Kaggle competitions using XGBoost, LightGBM, and CatBoost, with focus on ensemble learning and hyperparameter tuning.",
      image: "https://cdn.analyticsvidhya.com/wp-content/uploads/2020/06/Your-Guide-to-Getting-Started-with-Kaggle-Competitions-Featured-image.jpg",
      technologies: ["Python", "xgboost", "lightgbm", "catboost"],
      category: "machine learning",
      tags: ["kaggle competitions", "machine learning", "ensemble learning", "hyperparameter tuning"],
      githubLink: "https://github.com/SkikriHassane01/Kaggle-Cometitions",
      demoLink: "",
      date: "2023-05-06"
    },
    {
      id: 56,
      title: "Roadmap Web Design with HTML/CSS/JS",
      description: "Interactive learning roadmap website built with vanilla HTML, CSS, and JavaScript, featuring progress tracking and resource linking.",
      image: "https://www.codeur.com/blog/wp-content/uploads/2023/05/roadmap-marketing.jpg.webp",
      technologies: ["HTML", "CSS", "JavaScript", "Responsive Design"],
      category: "Other",
      tags: ["Web Development", "Educational", "Interactive Design", "Frontend"],
      githubLink: "https://github.com/SkikriHassane01/Webpage_Roadmap_design_using_HTML_CSS_JS",
      demoLink: "",
      date: "2023-12-30"
    },
    {
      id: 57,
      title: "TicTacToe Game Java Project",
      description: "Java implementation of the classic Tic-Tac-Toe game with GUI, player statistics, and configurable AI opponent difficulty levels.",
      image: "https://images.pexels.com/photos/28454507/pexels-photo-28454507.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2e",
      technologies: ["Java", "JavaFX", "Game Development", "AI"],
      category: "Other",
      tags: ["Game Development", "Java", "GUI Application", "AI Opponent"],
      githubLink: "https://github.com/SkikriHassane01/TicTacToe-Game-Java-Project",
      demoLink: "",
      date: "2023-11-04"
    },
    {
      id: 58,
      title: "Media Management Java Project",
      description: "Java application for organizing and managing media files (images, audio, video) with metadata editing, tagging, and search capabilities.",
      image: "https://cdn-images-1.medium.com/fit/t/1600/480/1*zJa7AhVE8Rt2c0LRAK4UdA.png",
      technologies: ["Java", "JavaFX", "File Management", "Database"],
      category: "Other",
      tags: ["Media Organization", "Java Application", "Desktop App", "File Management"],
      githubLink: "https://github.com/SkikriHassane01/Media-Management-JavaProject",
      demoLink: "",
      date: "2024-03-19"
    },
    {
      id: 59,
      title: "Car Reservation System",
      description: "Java-based car rental and reservation system with user authentication, vehicle inventory management, and reservation tracking.",
      image: "https://img.freepik.com/photos-gratuite/systeme-gps-dans-voiture-intelligente_53876-105375.jpg?t=st=1740869073~exp=1740872673~hmac=cddb00044a4adbaa7ba5c350150912decef5f4388d22eabcfc75527278ce9dca&w=1380",
      technologies: ["Java", "JDBC", "MySQL", "Swing"],
      category: "Other",
      tags: ["Reservation System", "Java", "Database Application", "Business Software"],
      githubLink: "https://github.com/SkikriHassane01/Manage-Car-Reservation-Java-Project",
      demoLink: "",
      date: "2023-02-08"
    },
    {
      id: 60,
      title: "Store Management C++ Project",
      description: "C++ application for retail store inventory and sales management, featuring stock tracking, purchase orders, and sales analytics.",
      image: "https://img.freepik.com/free-photo/young-man-working-warehouse-with-boxes_1303-16596.jpg?t=st=1740869497~exp=1740873097~hmac=e725f431febe0854a10b96dca3fc056a131c530a9339bb1e34ae782b10ce89f6&w=1380",
      technologies: ["C++", "OOP", "File Handling", "Data Structures"],
      category: "Other",
      tags: ["Inventory Management", "C++", "Business Application", "CRUD"],
      githubLink: "https://github.com/SkikriHassane01/StoreManagementCppProject",
      demoLink: "",
      date: "2023-03-13"
    },
    {
      id: 61,
      title: "Material Management C Project",
      description: "C language implementation of a material management system for tracking equipment, supplies, and maintenance schedules in an industrial setting.",
      image: "https://img.freepik.com/photos-gratuite/portrait-ouvrier-usine-bras-croises-debout-par-machine-industrielle_342744-182.jpg?t=st=1740869018~exp=1740872618~hmac=74a1797da0406e4b4786d884e270094549db62d5190590e4bd394cd98deed087&w=1380",
      technologies: ["C", "Data Structures", "File I/O", "Algorithms"],
      category: "Other",
      tags: ["Inventory Control", "C Programming", "Industrial Software", "Resource Management"],
      githubLink: "https://github.com/SkikriHassane01/Material_management-C-project",
      demoLink: "",
      date: "2024-09-21"
    },
  ];
  
  export default projectsData;